### ISSUE TITLE
[BUG] Parsing registry.yml nil pointer exception

### ISSUE THREAD

**Issue by ZhongqiXiao** [cnrancher/autok3s#273]
Hi, I run with native provider,and i want to delete cluster that I had created. 
here are some env info:
```bash
Version: {"gitVersion":"v0.4.0","gitCommit":"70c67fb47033330dab6deb20f0dff163d33ada7d","gitTreeState":"","buildDate":"2021-03-19T13:08:10Z","goVersion":"go1.16.2","compiler":"gc","platform":"linux/amd64"}
os: ubuntu 16.04
docker : 20.10.5
```
I run this command and get error:
```bash
# autok3s delete -p native myk3s
FATA[0000] [native] dose not support command: [delete]
```

when I tried to create new cluster with 
```
autok3s -d create --provider native --name anotherk3s --ssh-key-path ./ssh/id_rsa  --master-ips xx.xx.xx.xx --registry /etc/autok3s/registries.yaml --cluster --ui
```
got this error
```
time="2021-03-31T15:18:29+08:00" level=info msg="[native] executing create logic..."
time="2021-03-31T15:18:29+08:00" level=info msg="[native] executing init k3s cluster logic..."
time="2021-03-31T15:18:29+08:00" level=info msg="[native] creating k3s master-1..."
time="2021-03-31T15:18:29+08:00" level=info msg="=========================== Prompt Info ==========================="
time="2021-03-31T15:18:29+08:00" level=info msg="Use 'autok3s kubectl config use-context newk3s'"
time="2021-03-31T15:18:29+08:00" level=info msg="Use 'autok3s kubectl get pods -A' get POD status`"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x185924b]

goroutine 1 [running]:
github.com/cnrancher/autok3s/pkg/cluster.registryTLSMap(0xc00000fbf0, 0x1c, 0xc00000fbf0, 0x0)
	/go/src/github.com/cnrancher/autok3s/pkg/cluster/cluster.go:783 +0x10b
github.com/cnrancher/autok3s/pkg/cluster.handleRegistry(0xc000a1d320, 0xc00081cfc0, 0x309aa03, 0x8)
	/go/src/github.com/cnrancher/autok3s/pkg/cluster/cluster.go:727 +0x16b
github.com/cnrancher/autok3s/pkg/cluster.initMaster(0x30b01ca, 0x12, 0x0, 0x0, 0x0, 0x0, 0x7ffd32e427bc, 0xc, 0xc00059b950, 0x2b, ...)
	/go/src/github.com/cnrancher/autok3s/pkg/cluster/cluster.go:458 +0x109
github.com/cnrancher/autok3s/pkg/cluster.InitK3sCluster(0xc00081cfc0, 0xc0007b5c88, 0xc00081cfc0)
	/go/src/github.com/cnrancher/autok3s/pkg/cluster/cluster.go:114 +0x5fb
github.com/cnrancher/autok3s/pkg/providers/native.(*Native).CreateK3sCluster(0xc00069a3c0, 0x0, 0x0)
	/go/src/github.com/cnrancher/autok3s/pkg/providers/native/native.go:127 +0x466
github.com/cnrancher/autok3s/cmd.CreateCommand.func2(0x5480e80, 0xc000a9e540, 0x0, 0xc)
	/go/src/github.com/cnrancher/autok3s/cmd/create.go:68 +0x133
github.com/spf13/cobra.(*Command).execute(0x5480e80, 0xc00004e120, 0xc, 0xc, 0x5480e80, 0xc00004e120)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x5480be0, 0xc000a1ff28, 0xa, 0xa)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
	/go/src/github.com/cnrancher/autok3s/main.go:41 +0x3fa
```
I only have one VM, installed kubectl and autok3s, and master-ips is this VM

How do I delete old cluster and create new one?

**Comment by JacieChao** [comment]
@ZhongqiXiao Thank you for reporting. 
1. This is a bug when parsing `registry.yaml` file. We will fix it at `v0.4.1`. For workaround at the current version, you can remove the `configs.tls` key if you don't need `TLS` settings.
For example:
```
mirrors:
  docker.io:
    endpoint:
      - "https://mycustomreg.com:5000"
configs:
  "mycustomreg:5000":
    auth:
      username: xxxxxx # this is the registry username
      password: xxxxxx # this is the registry password
```
2. We don't support delete clusters for the `native` provider. If you want to uninstall the old cluster, you can run `sh /usr/local/bin/k3s-uninstall.sh` on your local VM(https://rancher.com/docs/k3s/latest/en/installation/uninstall).
