### ISSUE TITLE
[BUG] Failed to create Tencent Cloud cluster

### ISSUE THREAD

**Issue by kingsd041** [cnrancher/autok3s#416]
**Describe the bug**
Failed to create Tencent Cloud cluster

**To reproduce**
1. Use the Tencent provider to create a cluster with 1 master and 2 worker nodes
2. Tencent Cloud shows that all 3 VMs have been created successfully

**result**
autok3s failed to create k3s cluster, autok3s crashed

**Screenshots**

**Environments (please complete the following information):**
 - OS: [e.g. Darwin Bigsur] macos
 - AutoK3s Version [e.g. v0.4.0] 0.4.8

**Logs**

```
time="2022-03-22T11:18:52+08:00" level=info msg="[tencent] executing create logic..."
INFO[14298] [tencent] use existing key pair skey-natyhzqp
time="2022-03-22T11:18:52+08:00" level=info msg="[tencent] 1 masters and 2 workers will be added"
time="2022-03-22T11:18:52+08:00" level=info msg="[tencent] 1 number of master instances will be created"
time="2022-03-22T11:18:59+08:00" level=info msg="[tencent] 1 number of master instances successfully created"
time="2022-03-22T11:18:59+08:00" level=info msg="[tencent] 2 number of worker instances will be created"
time="2022-03-22T11:19:07+08:00" level=info msg="[tencent] 2 number of worker instances successfully created"
time="2022-03-22T11:19:07+08:00" level=info msg="[tencent] waiting for the instances [ins-q4h6trrj ins-hc2l5lnl ins-05816pfp] to be in `RUNNING` status..."
time="2022-03-22T11:19:37+08:00" level=info msg="[tencent] instances [ins-q4h6trrj ins-hc2l5lnl ins-05816pfp] are in `RUNNING` status"
time="2022-03-22T11:19:39+08:00" level=info msg="[tencent] executing init k3s cluster logic..."
time="2022-03-22T11:19:39+08:00" level=info msg="[tencent] creating k3s master-1..."
mirrors:
    docker.io:
        endpoint:
            - https://fogjl973.mirror.aliyuncs.com
            - https://registry-1.docker.io
configs: {}
auths: {}
time="2022-03-22T11:19:40+08:00" level=info msg="[cluster] k3s master command: curl -sLS http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn K3S_TOKEN='rancher' INSTALL_K3S_EXEC='server  --tls-san 140.143.225.51 --node-external-ip 140.143.225.51 --cluster-cidr 10.42.0.0/16' INSTALL_K3S_CHANNEL='stable' sh -"
[INFO]  Finding release for channel stable
[INFO]  Using v1.22.7+k3s1 as release
[INFO]  Downloading hash http://rancher-mirror.cnrancher.com/k3s/v1.22.7-k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary http://rancher-mirror.cnrancher.com/k3s/v1.22.7-k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
ERRO[14355] Error during subscribe websocket: close sent
time="2022-03-22T11:20:09+08:00" level=info msg="[tencent] successfully created k3s master-1"
time="2022-03-22T11:20:09+08:00" level=info msg="[tencent] creating k3s worker-1..."
time="2022-03-22T11:20:09+08:00" level=info msg="[tencent] creating k3s worker-2..."
ERRO[2022-03-22T11:21:53+08:00] [tencent] failed to generate kube client for cluster hailong-tencent-1: context "hailong-tencent-1.ap-beijing.tencent" does not exist
W0322 11:22:02.046378   18648 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
ERRO[2022-03-22T11:23:33+08:00] [tencent] failed to generate kube client for cluster hailong-tencent-1: context "hailong-tencent-1.ap-beijing.tencent" does not exist
ERRO[2022-03-22T11:24:33+08:00] [tencent] failed to generate kube client for cluster hailong-tencent-1: context "hailong-tencent-1.ap-beijing.tencent" does not exist




W0322 11:28:42.046260   18648 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
time="2022-03-22T11:29:39+08:00" level=error msg="[ssh-dialer] init dialer [ins-hc2l5lnl] error: timed out waiting for the condition"
panic: runtime error: index out of range [0] with length 0

goroutine 991 [running]:
github.com/cnrancher/autok3s/pkg/cluster.(*ProviderBase).initWorker(_, _, _, {_, _}, {_, _}, {_, _}, {0x0, ...}, ...)
	/Users/jacie/source/goproject/src/github.com/cnrancher/autok3s/pkg/cluster/cluster.go:538 +0x705
github.com/cnrancher/autok3s/pkg/cluster.(*ProviderBase).InitK3sCluster.func1(0x0, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...})
	/Users/jacie/source/goproject/src/github.com/cnrancher/autok3s/pkg/cluster/cluster.go:154 +0x2a9
created by github.com/cnrancher/autok3s/pkg/cluster.(*ProviderBase).InitK3sCluster
	/Users/jacie/source/goproject/src/github.com/cnrancher/autok3s/pkg/cluster/cluster.go:147 +0x1855
 ✘ ksd  ~/.autok3s 
```

**Comment by JacieChao** [comment]
@kingsd041 It seems like the Tencent Cloud VM(ins-hc2l5lnl) is not available to access due to the error `init dialer [ins-hc2l5lnl] error`. It will help to check the VM status from Tencent Dashboard(to make sure the public IP is available) when the issue occurs.
We have fixed the panic problem in v0.4.9, please feel free to reopen this issue if it still happens in v0.4.9.
